# Generated by Django 4.2.5 on 2023-10-03 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='time_creat',
            new_name='time_create',
        ),
    ]
